version: '3.8' # Specify compose file version

services:
  neo4j:
    image: neo4j:5.18.0 # Use a specific Neo4j version for reproducibility (check latest on Docker Hub if needed)
    container_name: temporal-graph-neo4j # A friendly name for the container
    ports:
      - "7474:7474" # Map host port 7474 to container port 7474 (Neo4j Browser HTTP)
      - "7687:7687" # Map host port 7687 to container port 7687 (Bolt driver connection)
    volumes:
      # Mount host directories into the container for data persistence
      # IMPORTANT: Create these 'neo4j/data' and 'neo4j/logs' folders in your project root first!
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      # You might also want to mount plugins or conf if needed later
      # - ./neo4j/plugins:/plugins
      # - ./neo4j/conf:/conf
    environment:
      # Set Neo4j authentication. Format: neo4j/<password>
      # !! CHANGE 'your_strong_password' !!
      - NEO4J_AUTH=neo4j/nvyVl2h3HrZkRv9EglNK
      # Optional: Adjust memory settings if needed (examples)
      # - NEO4J_server_memory_heap_initial__size=512m
      # - NEO4J_server_memory_heap_max__size=2G
      # Optional: Accept license agreement for Enterprise Edition features (if using Enterprise image)
      # - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    restart: unless-stopped # Optional: Restart the container unless manually stopped